package com.tschokkinen.doilikeithere.models;

/**
 * Class for selection items.
 * A new Selection is instantiated when RecyclerView is created.
 * @author Gavril Tschokkinen
 */

public class SelectionItem {
    private int id;
    private String name;
    private int weight;
    private Boolean hasBeenSelected;

    /**
     * SelectionItem constructor.
     *
     * @param  id  Id generated by the RecyclerView.
     * @param  name  Name of the item displayed on the RecyclerView.
     * @param  weight  The value of item displayed on the RecyclerView.
     *                 Used when calculating the total score for the review.
     */
    public SelectionItem(int id, String name, int weight) {
        this.id = id;
        this.name = name;
        this.weight = weight;
        this.hasBeenSelected = false;
    }

    /**
     * Get name of the SelectionItem.
     */
    public String getName() {
        return name;
    }

    /**
     * Get weight of the SelectionItem.
     */
    public int getWeight() { return weight; }

    /**
     * If selection item has been selected on the RecyclerView, hasBeenSelected is true,
     * otherwise false.
     */
    public void setHasBeenSelected() {
        if (!hasBeenSelected) {
            hasBeenSelected = true;
        } else {
            hasBeenSelected = false;
        }
    }

    /**
     * Get state of hasBeenSelected Boolean.
     */
    public Boolean getHasBeenSelected() {
        return hasBeenSelected;
    }

}
